### ISSUE TITLE
Throws exception when filtering cannot be done

### ISSUE THREAD

**Issue by Tomas2D** [artprima/query-filter-bundle#11]
Hello, firstly I would like to thank your for this pretty nice library! Good job.

I just would like to ask if there is some way to throw an exception when client wants to filter/sort by column which is not allowed or defined?

As I am looking through the code, I noticed that it can be easily done by putting that specific exception into `getSimpleSearchBy` method. 

```
// QueryFilter.php

private function getSimpleSearchBy(array $allowedCols, ?array $search): array
    {
        /** @var Filter[] $searchBy */
        $searchBy = [];

        if ($search === null) {
            return $searchBy;
        }

        foreach ($search as $key => $val) {
            if (!in_array($key, $allowedCols, true) || $val === null) {
            	throw new \Exception('Filter cannot be applied.'); // here
            }

            $searchBy[] = $this->getFilter($key, $val);
        }

        return $searchBy;
    }
```

Should I make pull request or you do not like the idea of getting warned because of usage invalid/disallowed filter.

Thanks!

**Comment by denisvmedia** [comment]
Thank you for your proposal. I have some additional thoughts on it. First of all, I agree that in some cases it might be useful to short-circuit the execution in case of invalid values submitted. However, I also think that changing the default behavior may be an unexpected and unpleasant effect for the existing users of the bundle.

So, what comes to my mind is extending `Artprima\QueryFilterBundle\QueryFilter\Config\ConfigInterface` and `Artprima\QueryFilterBundle\QueryFilter\Config\BaseConfig` by adding `public function setStrictColumns(bool $strict): self` and `public function isStrictColumns(): bool`. By default, it will return `false` and the behavior will remain as now. If set to `true` it will throw an exception instead of skipping an invalid value. And we'll have to add a new exception class `UnexpectedValueException` that will extend `\RuntimeException`.

The only drawback of this solution is that if someone directly implemented `ConfigInterface`, s/he will get a BC break. But I doubt that anyone really did that. And yet, adding a new setter and getter would not be a big deal I think.

Do you agree? Would you be willing to submit a PR for this feature @Tomas2D ?

**Comment by Tomas2D** [comment]
I agree. I will send a pull request at the evening or tomorrow.

**Comment by denisvmedia** [comment]
@Tomas2D thank you so much for your Merge Request. I merged it. If no issues reported, I'll merge it approximately in a week. For now you can use `dev-develop` in your `composer.json`.

**Comment by Tomas2D** [comment]
@denisvmedia perfect, thanks!

**Comment by Tomas2D** [comment]
When I use  `dev-develop` in my `composer.json` I am still getting the old version.

**Comment by denisvmedia** [comment]
Here is my composer.json (it was before set to the most recent release version of `query-filter-bundle`).

```
{
    "require": {
        "artprima/query-filter-bundle": "dev-develop"
    }
}
```

After I set it to `dev-develop`, I ran `composer update`:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing artprima/query-filter-bundle (1.4.0)
  - Installing artprima/query-filter-bundle (dev-develop e6876c3): Cloning e6876c3848 from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
35 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

As you see, `e6876c3` is the most recent commit of develop and it's where your changes were merged.

Can you show your `composer.json`?

**Comment by Tomas2D** [comment]
Sorry, it is working. My IDE just confused me. It works now.
